spring:
  config:
    activate:
      on-profile: test
  jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        use-new-id-generator-mappings: false
  datasource:
    hikari:
      jdbc-url:
      username:
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
