spring:
  application:
    name: raisedragon
  messages:
    encoding: UTF-8

# Swagger docs
springdoc:
  swagger-ui:
    path: /api-docs
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true
