jwt:
  secret-key: ENC(nFedRKX5zt00VoNk/11zZcZVAtdnl/AHTDJW74urxj103ameypl1NctWnJYl90thp8OS/DIP8B0oHXgvMVJ02TPFiMZes3Kf3/EPG9t/MnUKvjc4iz1HZ+F76oDcvxXheKiioRZkGt1b0g9iyh7PW4CKSo5T/rScgXsg2c+05bg=)

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(DJIgIfcvZJ7ju2w8KoINUm1ebLce2GSFbye2dF/r35Y60cXtfU5yQKzGUbght6o8IU9qKdUl/miUOfkdf4PKYxhYOgX9VDnJaEALtVc4myKmD33IOkfO1iFa5Gk5DtpC2dGYTMT+/Jp9aesxmmDcNqI/16GqWW7GJmq7E+4ZK0AtpIi12SpSLUNQd8squdo1)
    username: ENC(DjA+U5+0/2Sk6NYp/DpbV/QxGXyn5s46HRcEcijkJ1wu56xm+xdIzQPek2KHhG/c)
    password: ENC(NpEuFMBEM8g5CyWRcWEyeK5Lqq2YYMcpqB22uy9GJ19g1o+MR8dg+ST9QZ+gUZd1)
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true